language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - 7

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit -c test/phpunit.dist.xml  --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)